[[mapping]]
from = "artnet:32.0.0"
to = "sacn:32"

[[mapping]]
from = "artnet:34.0.0"
to = "sacn:34"

# lighting-1 port 1
[[target]]
universe = "artnet:0.0.0"
address = "10.50.1.64"
[[target]]
universe = "artnet:0.0.1"
address = "10.50.1.64"

# lighting-1 port 2
[[target]]
universe = "artnet:0.0.8"
address = "10.50.1.65"
[[target]]
universe = "artnet:0.0.9"
address = "10.50.1.65"

# lighting-2 port 1
[[target]]
universe = "artnet:0.0.2"
address = "10.50.1.72"
[[target]]
universe = "artnet:0.0.3"
address = "10.50.1.72"
[[target]]
universe = "artnet:0.0.4"
address = "10.50.1.72"
[[target]]
universe = "artnet:0.0.5"
address = "10.50.1.72"
[[target]]
universe = "artnet:0.0.6"
address = "10.50.1.72"

# lighting-2 port 2
[[target]]
universe = "artnet:0.0.10"
address = "10.50.1.73"
[[target]]
universe = "artnet:0.0.11"
address = "10.50.1.73"
[[target]]
universe = "artnet:0.0.12"
address = "10.50.1.73"
[[target]]
universe = "artnet:0.0.13"
address = "10.50.1.73"
[[target]]
universe = "artnet:0.0.14"
address = "10.50.1.73"

# 1M1
[[mapping]]
from = "sacn:70:361-396"
to = "artnet:9.0.0"

# 1M2
[[mapping]]
from = "sacn:70:397-432"
to = "artnet:10.0.0"

# 1M3
[[mapping]]
from = "sacn:70:433-468"
to = "artnet:11.0.0"

# 1M4
[[mapping]]
from = "sacn:70:469-504"
to = "artnet:12.0.0"

# 1M5
[[mapping]]
from = "sacn:71:361-396"
to = "artnet:13.0.0"

# 1M6
[[mapping]]
from = "sacn:71:397-432"
to = "artnet:14.0.0"

# 1P1
[[mapping]]
from = "sacn:71:1-360"
to = "artnet:0.0.2:1"

# 1P2
[[mapping]]
from = "sacn:72:1-150"
to = "artnet:0.0.2:361"
[[mapping]]
from = "sacn:72:151-360"
to = "artnet:0.0.3:1"

# 1P3
[[mapping]]
from = "sacn:73:1-300"
to = "artnet:0.0.3:211"
[[mapping]]
from = "sacn:73:301-360"
to = "artnet:0.0.4:1"

# 1P4
[[mapping]]
from = "sacn:74:1-360"
to = "artnet:0.0.4:61"

# 1P5
[[mapping]]
from = "sacn:75:1-90"
to = "artnet:0.0.4:421"
[[mapping]]
from = "sacn:75:91-360"
to = "artnet:0.0.5:1"

# 1P6
[[mapping]]
from = "sacn:76:1-240"
to = "artnet:0.0.5:271"
[[mapping]]
from = "sacn:76:241-360"
to = "artnet:0.0.6:1"

# 1P7
[[mapping]]
from = "sacn:77:1-360"
to = "artnet:0.0.10:1"

# 1P8
[[mapping]]
from = "sacn:78:1-150"
to = "artnet:0.0.10:361"
[[mapping]]
from = "sacn:78:151-360"
to = "artnet:0.0.11:1"

# 1P9
[[mapping]]
from = "sacn:79:1-300"
to = "artnet:0.0.11:211"
[[mapping]]
from = "sacn:79:301-360"
to = "artnet:0.0.12:1"

# 1P10
[[mapping]]
from = "sacn:80:1-360"
to = "artnet:0.0.12:61"

# 1P11
[[mapping]]
from = "sacn:81:1-90"
to = "artnet:0.0.12:421"
[[mapping]]
from = "sacn:81:91-360"
to = "artnet:0.0.13:1"

# 1P12
[[mapping]]
from = "sacn:82:1-240"
to = "artnet:0.0.13:271"
[[mapping]]
from = "sacn:82:241-360"
to = "artnet:0.0.14:1"

# 2P1
[[mapping]]
from = "sacn:64:361-450"
to = "artnet:0.0.0:1"

# 2P2
[[mapping]]
from = "sacn:65:361-450"
to = "artnet:0.0.0:91"

# 2P3
[[mapping]]
from = "sacn:64:181-360"
to = "artnet:0.0.0:181"

# 2P4
[[mapping]]
from = "sacn:65:1-150"
to = "artnet:0.0.0:361"
[[mapping]]
from = "sacn:65:151-180"
to = "artnet:0.0.1:1"

# 2P5
[[mapping]]
from = "sacn:65:181-360"
to = "artnet:0.0.1:31"

# 2P6
[[mapping]]
from = "sacn:64:1-181"
to = "artnet:0.0.1:211"

# 2P7
[[mapping]]
from = "sacn:66:361-450"
to = "artnet:0.0.1:391"

# 3P1
[[mapping]]
from = "sacn:72:361-450"
to = "artnet:0.0.8:1"

# 3P2
[[mapping]]
from = "sacn:66:1-180"
to = "artnet:0.0.8:91"

# 3P3
[[mapping]]
from = "sacn:66:181-360"
to = "artnet:0.0.8:271"

# 3P4
[[mapping]]
from = "sacn:70:1-60"
to = "artnet:0.0.8:451"
[[mapping]]
from = "sacn:70:61-180"
to = "artnet:0.0.9:1"

# 3P5
[[mapping]]
from = "sacn:70:181-360"
to = "artnet:0.0.9:121"

# 3P6
[[mapping]]
from = "sacn:73:361-450"
to = "artnet:0.0.9:301"

# 3P6
[[mapping]]
from = "sacn:74:361-450"
to = "artnet:0.0.9:391"
